global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
        - localhost:9090  # Prometheus itself

  - job_name: backend  # New job for your NestJS app
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /backend/metrics  # Use the correct metrics path
    scheme: http
    static_configs:
      - targets:
        - backend:4000  # Use the correct address and port for your NestJS app